config/routes.rb
Piaday::Application.routes.draw do
  root to: 'pages#home'

  resources :users
  resources :sessions,only: [:new,:create,:destroy]
  resources :password_resets
  resources :email_confirmations
  resources :pi
  resources :e
  resources :phi

  match '/about',to: 'pages#about'
  match '/howto',to: 'pages#howto'
  match '/signup',to: 'users#new'
  match '/signin',to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',via: :delete

end

app/models/phi.rb
class Phi < ActiveRecord::Base
  attr_accessible :digits_known, :next_test, :user_id
  validates :user_id,presence: :true

  belongs_to :user
end

app/controllers/phi_controller.rb
class PhiController < ApplicationController
  before_filter :get_phi,only: [:edit,:update]
  before_filter :signed_in_user
  before_filter :confirmed_user

  include PhiHelper

  def new
  end

  def create
    @phi = Phi.new
    if !test_length(params[:phi])
      flash[:error] = "Sorry, the site currently only supports up to 200 digits of phi, please send an email to me asking for more and I'll update it as soon as I can"
      redirect_to root_path
    elsif
      @phi.digits_known = phi_to_digits(params[:phi])
      @phi.next_test = current_user.test_frequency.days.from_now
      if (@phi.digits_known > 0)
        current_user.phi = @phi
        current_user.phi.save!
        flash[:success] = "You know " + @phi.digits_known.to_s + " digits of phi!"
        redirect_to root_path
      else
        flash[:error] = "You typed that incorrectly."
        render 'new'
      end
    end
  end

  def edit
    render action: 'learn'
  end

  def update
    if(params.has_key?(:phi) && test_length(params[:phi]))             # Must be a test!
      if temp = phi_to_digits(params[:phi])
        if temp >= @phi.digits_known      # Test success!
          @phi.digits_known = temp
          @phi.next_test = current_user.test_frequency.days.from_now
          @phi.save!
          flash[:success] = "You passed! You now know " + @phi.digits_known.to_s + " digits of phi!"
          redirect_to root_path
        elsif params[:reset]              # Reset digits
          @phi.digits_known = temp
          @phi.next_test = current_user.test_frequency.days.from_now
          @phi.save!
          flash[:success] = "You now know " + @phi.digits_known.to_s + " digits of phi!"
          redirect_to root_path
        elsif params[:skip]               # Skip test
          @phi.next_test = current_user.test_frequency.days.from_now
          @phi.save!
          flash[:success] = "Test skipped!(be sure to do your next one though!)"
          redirect_to edit_phi_path(@phi)
        else                              # Test failure!
          flash[:error] = "You seem to have entered something incorrectly or forgetten some digits of phi!, please try again,
                         or click \"Skip Test\" "
          redirect_to edit_phi_path(@phi)
        end
      else                                # Test gone wrong :O
        flash[:error] = "You entered something wrong, remember to begin with 3.14..."
        redirect_to edit_phi_path(@phi)
      end
    elsif(!test_length(params[:phi]))
      flash[:error] = "Sorry, the site currently only supports up to 200 digits of phi, please send an email to me asking for more and I'll update it as soon as I can"
      redirect_to root_path
    elsif(params[:test?])                 # Not a test, but check if they want a test now
      @phi.next_test = Time.now
      @phi.save!
      redirect_to edit_phi_path(@phi)
    else                                  # Not a test, don't want one either
      @phi.digits_known += 1
      @phi.save!
      flash[:success] = "You now know " + @phi.digits_known.to_s + " digits of phi!"
      redirect_to root_path
    end
  end

  private

  def test_length(number)
    if number.to_s.length > 200
      return false
    else
      return true
    end
  end

  def get_phi
    @phi = current_user.phi
  end
end

app/helpers/phi_helper.rb
module PhiHelper
  # I realize that the code here is hardly memory efficient, or even 
  # remotely well optomized, but this isn't exactly a high strain app 
  # at this point, with just a user or two this wont really hurt much.

  # yes it's not formatted properly for linebreaks, oh well
  REALPHI = BigDecimal.new("1.61803398874989484820458683436563811772030917980576286213544862270526046281890244970720720418939113748475408807538689175212663386222353693179318006076672635443338908659593958290563832266131992829026788")

  REALPHIARRAY = REALPHI.to_s.scan(/\d/)

  def phi_to_digits(number)
    @phiarray = to_array(number)
    REALPHIARRAY.each_index do |index|
      if REALPHIARRAY[index] != @phiarray[index]
        return index
      end
    end
  end

  def digits_to_phi(number)
    REALPHIARRAY.first(number).join(' ')
  end

  def next_digit(number)
    REALPHIARRAY[number]
  end

  def to_array(longnum)
    longnum.to_s.scan(/\d/)
  end

  def phi_days_to_next_test
    numdays = (@phi.next_test - Time.now) / (24 * 60 * 60)
    numdays.truncate
  end
end

app/views/phi/learn.html.erb
<% provide :title,'Learn Phi' %>
<h2>Learn Phi</h2>
<% if @phi.next_test < Time.now %>
  <h2>Test Time!</h2>
  <h4>Please enter as many digits of phi as you know.</h4>
  <%= form_tag phi_path,method: :put do %>
    <%= text_area_tag :phi,params[:phi] %>

    <%= submit_tag "Submit",class: "button" %><br />

    <%= submit_tag "Reset digits known",{class: "button",name: "reset"} %><br />

    (be sure to enter as many as you know above though!)
    <br /><br />
    <%= submit_tag "Skip test",{class: "button",name: "skip"} %>
  <% end %>
  <% else %>
  <h4>So far, you know:<br />
    <h4><span class="digits"><%= digits_to_phi(@phi.digits_known) %></span></h4></h4>
  <h2>Your next number is:<br />
    <h2><span class="nextnum"><%= next_digit(@phi.digits_known) %></span></h4></h4>
  <%= form_tag phi_path,method: :put do %>
    <%= label_tag "Test now?" %>
    <%= check_box_tag "test?" %><br />
    <%= submit_tag "I know this!",class: "button" %>
  <% end %>

  Your next test will be in <%= pluralize(phi_days_to_next_test,"day") %>.
<% end %>

app/views/phi/new.html.erb
<% provide :title,'Phi' %>
<h2>Initial Test</h2>
<p>Please enter as many digits of phi as you know (startigng with 1.61).</p>
<div class="form">
  <%= form_tag phi_index_path do %>
    <%= text_area_tag :phi,params[:phi] %>

    <%= submit_tag "Submit",class: "button" %>
  <% end %>
</div>