config/routes.rb
Piaday::Application.routes.draw do
  root to: 'pages#home'

  resources :users
  resources :sessions,only: [:new,:create,:destroy]
  resources :password_resets
  resources :email_confirmations
  resources :pi
  resources :e
  resources :phi

  match '/about',to: 'pages#about'
  match '/howto',to: 'pages#howto'
  match '/signup',to: 'users#new'
  match '/signin',to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',via: :delete

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_window">
    <div class="error">
      The form contains <%= pluralize(object.errors.count,"error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_not_signed_in.html.erb
<div>
  <h1>Welcome!</h1>

  <%= link_to "Sign in",signin_path,class: "button" %><br /><br />
  <%= link_to "Sign up",signup_path,class: "button" %><br /><br />
  <%= link_to "How it works",howto_path,class: "button" %>
</div>

app/views/shared/_signed_in.html.erb
<% if current_user.pi %>
  <%= link_to image_tag("pi-link.png",alt: "Pi"),edit_pi_path(current_user.pi),class: "pibutton" %><br />
<% else %>
  <%= link_to image_tag("pi-link.png",alt:"Pi"),new_pi_path,class: "pibutton" %><br />
<% end %>
<% if current_user.e %>
  <%= link_to image_tag("e-link.png",alt: "e"),edit_e_path(current_user.e),class: "pibutton" %><br />
<% else %>
  <%= link_to image_tag("e-link.png",alt: "e"),new_e_path,class: "pibutton" %><br />
<% end %>
<% if current_user.use_tau %>
  <% if current_user.phi %>
    <%= link_to image_tag("tau-link.png",alt: "Tau"),edit_phi_path(current_user.phi),class: "pibutton" %>
  <% else %>
    <%= link_to image_tag("tau-link.png",alt: "Tau"),new_phi_path,class: "pibutton" %>
  <% end %>
<% else %>
  <% if current_user.phi %>
    <%= link_to image_tag("phi-link.png",alt: "Phi"),edit_phi_path(current_user.phi),class: "pibutton" %>
  <% else %>
    <%= link_to image_tag("phi-link.png",alt: "Phi"),new_phi_path,class: "pibutton" %>
  <% end %>
<% end %>