config/routes.rb
Piaday::Application.routes.draw do
  root to: 'pages#home'

  resources :users
  resources :sessions,only: [:new,:create,:destroy]
  resources :password_resets
  resources :email_confirmations
  resources :pi
  resources :e
  resources :phi

  match '/about',to: 'pages#about'
  match '/howto',to: 'pages#howto'
  match '/signup',to: 'users#new'
  match '/signin',to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',via: :delete

end

app/models/pi.rb
class Pi < ActiveRecord::Base
  attr_accessible :digits_known, :next_test, :user_id
  validates :user_id,presence: :true

  belongs_to :user
end

app/controllers/pi_controller.rb
class PiController < ApplicationController
  before_filter :get_pi,only: [:edit,:update]
  before_filter :signed_in_user
  before_filter :confirmed_user

  include PiHelper

  def new
  end

  def create
    @pi = Pi.new
    if !test_length(params[:pi])
      flash[:error] = "Sorry, the site currently only supports up to 200 digits of pi, please send an email to me asking for more and I'll update it as soon as I can"
      redirect_to root_path
    elsif test_length(params[:pi])
      @pi.digits_known = pi_to_digits(params[:pi])
      @pi.next_test = current_user.test_frequency.days.from_now
      if (@pi.digits_known > 0)
        current_user.pi = @pi
        @pi.save!
        flash[:success] = "You know " + @pi.digits_known.to_s + " digits of pi!"
        redirect_to root_path
      else
        flash[:error] = "You typed that incorrectly."
        render 'new'
      end
    end
  end

  def edit
    render action: 'learn'
  end

  def update
    if(params.has_key?(:pi) && test_length(params[:pi]))              # Must be a test!
      if temp = pi_to_digits(params[:pi])
        if temp >= @pi.digits_known       # Test success!
          @pi.digits_known = temp
          @pi.next_test = current_user.test_frequency.days.from_now
          @pi.save!
          flash[:success] = "You passed! You now know " + @pi.digits_known.to_s + " digits of pi!"
          redirect_to root_path
        elsif params[:reset]              # Reset digits
          @pi.digits_known = temp
          @pi.next_test = current_user.test_frequency.days.from_now
          @pi.save!
          flash[:success] = "You now know " + @pi.digits_known.to_s + " digits of pi!"
          redirect_to root_path
        elsif params[:skip]               # Skip test
          @pi.next_test = current_user.test_frequency.days.from_now
          @pi.save!
          flash[:success] = "Test skipped!(be sure to do your next one though!)"
          redirect_to edit_pi_path(@pi)
        else                              # Test failure!
          flash[:error] = "You seem to have entered something incorrectly or forgetten some digits of pi!, please try again,
                         or reset how many digits you know"
                         redirect_to edit_pi_path(@pi)
        end
      else                                # Test gone wrong
        flash[:error] = "You entered something wrong, remember to begin with 3.14..."
        redirect_to edit_pi_path(@pi)
      end
    elsif(!test_length(params[:pi]))
      flash[:error] = "Sorry, the site currently only supports up to 200 digits of pi, please send an email to me asking for more and I'll update it as soon as I can"
      redirect_to root_path
    elsif(params[:test?])                 # Not a test, but check if they want a test now
      @pi.next_test = Time.now
      @pi.save!
      redirect_to edit_pi_path(@pi)
    else                                  # Not a test, don't want one either
      @pi.digits_known += 1
      @pi.save!
      flash[:success] = "You now know " + @pi.digits_known.to_s + " digits of pi!"
      redirect_to root_path
    end
  end

  private

  def test_length(number)
    if number.to_s.length > 200
      return false
    else
      return true
    end
  end

  def get_pi
    @pi = current_user.pi
  end
end

app/helpers/pi_helper.rb
module PiHelper
  # I realize that the code here is hardly memory efficient, or even 
  # remotely well optomized, but this isn't exactly a high strain app 
  # at this point, with just a user or two this wont really hurt much.

  # yes it's not formatted properly for linebreaks, oh well
  REALPI = BigDecimal.new("3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196")

  REALPIARRAY = REALPI.to_s.scan(/\d/)

  def pi_to_digits(number)
    @piarray = to_array(number)
    REALPIARRAY.each_index do |index|
      if REALPIARRAY[index] != @piarray[index]
        return index
      end
    end
  end

  def digits_to_pi(number)
    REALPIARRAY.first(number).join(' ')
  end

  def next_digit(number)
    REALPIARRAY[number]
  end

  def to_array(longnum)
    longnum.to_s.scan(/\d/)
  end

  def pi_days_to_next_test
    numdays = (@pi.next_test - Time.now) / (24 * 60 * 60)
    numdays.truncate
  end
end

app/views/pi/learn.html.erb
<% provide :title,'Learn Pi' %>
<h2>Learn Pi</h2>
<% if @pi.next_test < Time.now %>
  <h2>Test Time!</h2>
  <h4>Please enter as many digits of pi as you know.</h4>
  <%= form_tag pi_path,method: :put do %>
    <%= text_area_tag :pi,params[:pi] %>

    <%= submit_tag "Submit",class: "button" %><br />

    <%= submit_tag "Reset digits known",{class: "button",name: "reset"} %><br />
    
    (be sure to enter as many as you know above though!)
    <br /> <br />
    <%= submit_tag "Skip test",{class: "button",name: "skip"} %>
  <% end %>
<% else %>
  <h4>So far, you know:<br />
    <h4><span class="digits"><%= digits_to_pi(@pi.digits_known) %></span></h4></h4>
  <h2>Your next number is:<br />
    <h2><span class="nextnum"><%= next_digit(@pi.digits_known) %></span></h2></h2>
  <%= form_tag pi_path,method: :put do %>
    <%= label_tag "Test now?" %>
    <%= check_box_tag "test?" %><br />
    <%= submit_tag "I know this!",class: "button" %>
  <% end %>

  Your next test will be in <%= pluralize(pi_days_to_next_test,"day") %>.
<% end %>

app/views/pi/new.html.erb
<% provide :title,'Pi' %>
<h2>Initial Test</h2>
<p>Please enter as many digits of pi as you know (starting with 3.14).</p>
<div class="form">
  <%= form_tag pi_index_path do %>
    <%= text_area_tag :pi,params[:pi] %>

    <%= submit_tag "Submit",class: "button" %>
  <% end %>
</div>