config/routes.rb
Piaday::Application.routes.draw do
  root to: 'pages#home'

  resources :users
  resources :sessions,only: [:new,:create,:destroy]
  resources :password_resets
  resources :email_confirmations
  resources :pi
  resources :e
  resources :phi

  match '/about',to: 'pages#about'
  match '/howto',to: 'pages#howto'
  match '/signup',to: 'users#new'
  match '/signin',to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',via: :delete

end

app/views/layouts/_footer.html.erb
<div id="ads">
</div>
<footer class="footer">
  <small>
    &copy 2012 <a href="http://www.somestupidwebsite.com">Tom McLeod</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",about_path %></li>
      <li><%= link_to "How it works",howto_path %></li>
      <li><a href="http://www.somestupidwebsite.com/email/">Contact</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% if signed_in? %>
    <%= link_to "Home",root_url,class: "button" %>
    <%= link_to "Sign out",signout_path,method:"delete",class: "button" %>
    <%= link_to "Settings",edit_user_path(current_user),class: "button" %>
  <% end %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pi a Day! (<%= yield :title %>)</title>
    <link rel="shortcut icon" href="/assets/favicon.gif">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <% if !signed_in? %>
        <%= link_to image_tag("pi-banner.png",alt: "Pi a Day"),root_path %>
      <% end %>
      <% flash.each do |key,value| %>
        <%= content_tag(:div,value,class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <div id="debug">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>